Controllers/MassController.cs
using Microsoft.AspNetCore.Mvc;
using NdaReservation.Models;

namespace NdaReservation.Controllers
{
    public class MassController : Controller
    {
        private IMassRepository m_massRepository;

        public MassController(IMassRepository massRepository)
        {
            m_massRepository = massRepository;
        }
        public ViewResult Index() // on affiche les messes déjà créé
        {
            return View(m_massRepository.Messes);
        }
        
        [HttpGet]
        public IActionResult Create() => View();
        //public IActionResult Create() => View("Edit", new Mass());
        
        [HttpPost]
        public IActionResult Create(Mass messe)
        {
            if(ModelState.IsValid)
            {
                // on enregistre la messe créé
                m_massRepository.SaveMass(messe);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(messe);//donne moi l'accord / promesse
            }
        }
        // création du reste des méthodes
        [HttpGet]
        public IActionResult Edit(int massID)
        {
            return View("Index");
        }
        [HttpGet]
        public IActionResult Delete(int massID)
        {
            return View("Index");
        }
    }
}

Views/Mass/Create.cshtml
@model NdaReservation.Models.Mass

@{
    ViewData["Title"] = "Créer une messe";
    Layout = "_AdminLayout";
}

<h2>Créer une messe</h2>
<hr />
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <form method="POST">
                <div class="form-group">
                    <label asp-for="DayOfTheWeek">Choisir le jour de la messe</label>
                    <div>
                        <select asp-for="DayOfTheWeek">
                            <option value="">Choisir le jour</option>
                            <option value="lundi">Lundi</option>
                            <option value="mardi">Mardi</option>
                            <option value="mercredi">Mercredi</option>
                            <option value="jeudi">Jeudi</option>
                            <option value="vendredi">Vendredi</option>
                            <option value="samedi">Samedi</option>
                            <option value="dimanche">Dimanche</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="HourOfCelebration">Choisir le jour de la messe</label>
                    <div>
                        <select asp-for="HourOfCelebration">
                            <option value="">Choisir l'heure de la célébration</option>
                            <option value="08:00:00">08:00 AM</option>
                            <option value="08:30 00">08:30 AM</option>
                            <option value="09:00:00">09:00 AM</option>
                            <option value="09:30:00">09:30 AM</option>
                            <option value="10:00:00">10:00 AM</option>
                            <option value="10:30:00">10:30 AM</option>
                            <option value="11:00:00">11:00 AM</option>
                            <option value="11:30:00">11:30 AM</option>
                            <option value="12:00:00">12:00 PM</option>
                            <option value="12:30:00">12:30 PM</option>
                            <option value="13:00:00">01:00 PM</option>
                            <option value="13:30:00">01:30 PM</option>
                            <option value="14:00:00">02:00 PM</option>
                            <option value="14:30:00">02:30 PM</option>
                            <option value="15:00:00">03:00 PM</option>
                            <option value="15:30:00">03:30 PM</option>
                            <option value="16:00:00">04:00 PM</option>
                            <option value="16:30:00">04:30 PM</option>
                            <option value="17:00:00">05:00 PM</option>
                            <option value="17:30:00">05:30 PM</option>
                            <option value="18:00:00">06:00 PM</option>
                            <option value="18:30:00">06:30 PM</option>
                            <option value="19:00:00">07:00 PM</option>
                            <option value="19:30:00">07:30 PM</option>
                            <option value="20:00:00">08:00 PM</option>
                        </select>
                    </div>
                </div>
                <div class="pager">
                    <a class="btn btn-primary previous">Annuler</a>
                    <button type="submit" class="btn btn-primary">Ajouter une messe</button>
                </div>
            </form>
        </div>
    </div>
</div>

Views/Mass/Index.cshtml
@model IQueryable<Mass>

@{
    ViewData["Title"] = "Liste des messes";
    Layout ="_AdminLayout";
}
<div>
    <a asp-controller="Mass" asp-action="Create">Créer une messe</a>
    <h3>Messes disponibles pour être reservée</h3>
    <hr />
    @if (Model.Count() != 0)
    {
        <div class="table-responsive">
            <table class="table">
                <thead class="thead-light">
                    <tr>
                        <th>Jour de la messe</th>
                        <th>Heure de la messe</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var r in Model)
                    {
                        <tr>
                            <td>@r.DayOfTheWeek</td>
                            <td>@r.HourOfCelebration</td>
                            <td>
                                <a asp-model="Mass" asp-action="Edit">Modifier</a> |
                                <a asp-model="Mass" asp-action="Delete">Effacer</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div> 
    }
    else
    {
        <span>Il n'y a pas de messes disponible pour l'instant</span>
    }
</div>