Models/MassActivation.cs
using System;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace NdaReservation.Models
{
    public class MassActivation
    {
        [BindNever]
        public long MassActivationID { get; set; }
        [BindNever]
        public DateTime MassDateTime { get; set; }
        [BindNever]
        public bool IsOpened { get; set; }
    }
}

Models/ViewModels/MassActivationViewModel.cs
using System.Collections.Generic;

namespace NdaReservation.Models.ViewModels
{
    public class MassActivationViewModel
    {
        public IEnumerable<MassActivation> MassesToActivate { get; set; }
        public IDictionary<int, string> ListOfMonths { get; set; }
    }
}

Controllers/MassActivationController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using NdaReservation.Models;
using NdaReservation.Models.ViewModels;
using NdaReservation.Infrastructure;


namespace NdaReservation.Controllers
{
    public class MassActivationController : Controller
    {
        private IMassRepository m_massRepository;
        private IMassActivationRepository m_massActivationRepository;
        private NdaDbContext m_applicationContex;

        public MassActivationController(
            IMassRepository massRepository, 
            IMassActivationRepository massActivationRepository,
            NdaDbContext ctx
        ){
            m_massRepository = massRepository;
            m_massActivationRepository = massActivationRepository;
            m_applicationContex = ctx;
        }

        public ViewResult Index() // on affiche le tableau du mois avec des messes activées ou non
        {
            return View( new MassActivationViewModel {
                MassesToActivate = m_massActivationRepository.ActiveMasses,
                ListOfMonths = Utilities.GetMonthsOfTheYear()
            });
        }

        [HttpPost]
        public IActionResult ActivateMass(int MonthToActivate) // on affiche le tableau du mois avec des messes activées ou non
        {
            if(ModelState.IsValid)
            {
                DateTime firstday = Utilities.GetFirstDayOfTheMonth(MonthToActivate);
                DateTime lastday = Utilities.GetLastDayOfTheMonth(MonthToActivate);
                do
                {
                    foreach(var mass in m_massRepository.Messes)
                    {
                        if(mass.DayOfTheWeek.ToLower() == firstday.ToString("dddd", new System.Globalization.CultureInfo("fr-FR")))
                        {
                            m_applicationContex.ActiveMasses.AddRange(
                                new MassActivation {
                                    MassDateTime = Utilities.GetMassTime(mass.HourOfCelebration, firstday),
                                    IsOpened = true
                                }
                            );
                        }
                    }
                    m_applicationContex.SaveChanges();
                    firstday = firstday.AddDays(1);
                }while(firstday <= lastday);
                return RedirectToAction(nameof(Details));
            }
            return View("Index");
        }

        [HttpGet]
        public ViewResult Details(int selectedMonth)
        {
            if( selectedMonth == 0 ){ // || selectedMonth == DateTime.Today.Month get the default month of the current year{
                
                //TempData["m"] = DateTime.Today.Month;
                ViewBag.Selection = DateTime.Today.Month;
                return View( new MassActivationViewModel {

                    MassesToActivate = m_massActivationRepository.ActiveMasses.Where( m =>
                                                                m.MassDateTime.Month == DateTime.Today.Month),
                    ListOfMonths = Utilities.GetMonthsOfTheYear()
                });
            }
            else{ // get view for a specific month

                ViewBag.Selection = selectedMonth;
                return View( new MassActivationViewModel {

                    MassesToActivate = m_massActivationRepository.ActiveMasses.Where( m =>
                                                                m.MassDateTime.Month == selectedMonth),
                    ListOfMonths = Utilities.GetMonthsOfTheYear()
                });
            }

        }
    }
}

Views/MassActivation/Details.cshtml
@model MassActivationViewModel

@{
    ViewData["Title"] = "Messes disponibles à être reservée";
    Layout ="_AdminLayout";
}
<div>
    <h3>Messes mensuelles ouvertes pour la réservation</h3>
    <hr />
    <div>
        <form class="form-inline" asp-controller="MassActivation" asp-action="Details" method="GET">
            <div class="form-group">
                <label for="selectedMonth"> Messes disponible pour le mois de :</label>
                <select class="form-control" id="selectedMonth" name="selectedMonth">
                    <option value="0"> Selectionner le mois </option>
                    @foreach (KeyValuePair<int, string> month  in Model.ListOfMonths){
                        @if(ViewBag.Selection == month.Key){
                            <option selected value="@month.Key">@month.Value</option>
                        }
                        else{
                            <option value="@month.Key">@month.Value</option>
                        }   
                    }
                </select>
            </div>
            <div>
                <button type="submit" class="btn btn-primary"> Voir les messes</button>
            </div>
        </form>
    </div>
    <hr />
    <div class="table-responsive">
        <table class="table">
            <thead class="thead-light">
                <tr>
                    <th>ID de la messe</th>
                    <th>Jour de la messe</th>
                    <th>Heure de la messe</th>
                    <th>Prêt pour Réservation</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @if(Model.MassesToActivate.Count() > 0)
                {
                    @foreach (var messe in Model.MassesToActivate)
                    {
                        <tr>
                            <td>@messe.MassActivationID</td>
                            <td>@messe.MassDateTime.ToString("D", new System.Globalization.CultureInfo("fr-FR"))</td>
                            <td>@messe.MassDateTime.ToString("HH:mm:ss")</td>
                            <td>@messe.IsOpened</td>
                            <td><a class="btn btn-warming">Modifier</a></td>
                        </tr>
                    }
                }
                else{
                    <tr>
                        <td colspan="5">
                            Aucune messe disponible pour être reservée
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Views/MassActivation/Index.cshtml
@model MassActivationViewModel

@{
    ViewData["Title"] = "Activer une réservation";
    Layout ="_AdminLayout";
}
<div>
    <h3>Rendre disponible la messe pour activer la réservation</h3>
    <hr />
    <div>
        <div class="table-responsive">
            <table class="table">
                <thead class="thead-light">
                    <tr>
                        <th>Mois de l'année</th>
                        <th>Etat de réservation</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (KeyValuePair<int, string> month  in Model.ListOfMonths)
                    {
                        <tr>
                            <td>@month.Value</td>
                            <td>
                                <form asp-controller="MassActivation" asp-action="ActivateMass" method="POST">
                                    <input type="hidden" name="MonthToActivate" value="@month.Key" />
                                    <button class="btn btn-warning">Activer</button>
                                    |<a>Details</a>
                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div> 
    </div>
</div>